server:
  port: 8080
# Spring 配置

spring:
  # 文件上传大小限制
  multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  # 模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    # 非规范html
    mode: LEGACYHTML5
    encoding: utf-8
    # 设置模板缓存
    cache: false
  # 静态资源配置
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
